name: Databricks API Action
description: 'The custom action provide ability to call Databricks for Automated Deployment'
author: Nepal Singh (Taapey Labs)
branding:
  icon: 'arrow-up-right'
  color: 'blue'
inputs:
  url:
    description: 'Databicks Api'
    required: true
  access_token:
    description: 'PAT for databricks'
    required: true
  method:
    description: 'GET/POST/PUT'
    required: true
    default: 'GET'
  json_data:
    description: 'Data for post Request'
    required: false
    default: ''
outputs:
  response:
    description: 'Response from API'
  status:
    description: 'Status returned by API'
runs:
  using: 'node20'
  main: 'dist/index.js'
  pre: 'setup.js'
  pre-if: runner.os == 'linux'
  post: 'cleanup.js'
  post-if: runner.os == 'linux'
