name: first workflow
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: call custom action
        id: call_api
        uses: ./.github/actions/api_action
        with:
          url: '${{secrets.DATABRICKS_API_URL}}'
          access_token: '${{secrets.DATABRICKS_ACCESS_TOKEN}}'
          method: 'GET'
      - name: run echo
        run: echo "Hello first workflow"
      - name: print the outputs
        run: echo Response ${{steps.call_api.output.response}}, status ${{steps.call_api.output.status}}
