name: Sample Databricks API Action
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout latest code
        uses: actions/checkout@main

      - name: call custom action
        id: access_api
        uses: ./
        with:
          url: '${{secrets.DATABRICKS_API_URL}}'
          accessToken: '${{secrets.DATABRICKS_ACCESS_TOKEN}}'
          method: 'GET'
      - name: print the outputs
        run: echo Response ${{steps.access_api.outputs.response}}, status ${{steps.access_api.outputs.status}}
